package com.ombp.cloud.app.ui.constants;

public interface AlertEventConstants {

	String SMS_TYPE_OTP = "SMS_TYPE_OTP";
	
	String SMS_TYPE_PT_REGISTRATION = "SMS_TYPE_PT_REGISTRATION";
	
	String SMS_TYPE_CALL_PT_REPORT_READY = "SMS_TYPE_CALL_PT_REPORT_READY";
	
	String SMS_TYPE_SHARE_REPORT_LINK = "SMS_TYPE_SHARE_REPORT_LINK";
	
	String SMS_TYPE_PT_REFERRED = "SMS_TYPE_PT_REFERRED";
	
	String SMS_TYPE_PT_REFERRED_TO_PT = "SMS_TYPE_PT_REFERRED_TO_PT";
	
	String SMS_TYPE_PT_REFERRED_TO_REFDOC = "SMS_TYPE_PT_REFERRED_TO_REFDOC";
	
	String SMS_TYPE_APPOINTMENT_BOOKING_TO_PT = "SMS_TYPE_APPOINTMENT_BOOKING_TO_PT";
	
	String SMS_TYPE_ONLINE_APPOINTMENT_BOOKING = "SMS_TYPE_ONLINE_APPOINTMENT_BOOKING";
	
	String EMAIL_TYPE_PT_REFERRED = "EMAIL_TYPE_PT_REFERRED";
	
	String EMAIL_TYPE_PT_REFERRED_TO_PT = "EMAIL_TYPE_PT_REFERRED_TO_PT";
	
	String EMAIL_TYPE_PT_REFERRED_TO_REFDOC = "EMAIL_TYPE_PT_REFERRED_TO_REFDOC";
	
	String EMAIL_TYPE_ONLINE_APPT_BOOKING_TO_PT = "EMAIL_TYPE_ONLINE_APPT_BOOKING_TO_PT";
	
	String EMAIL_TYPE_ONLINE_APPT_BOOKING = "EMAIL_TYPE_ONLINE_APPT_BOOKING";
	
	String EMAIL_TYPE_PT_REGISTERED = "EMAIL_TYPE_PT_REGISTERED";
	
	String EMAIL_TYPE_PT_APPT_CREATED = "EMAIL_TYPE_PT_APPT_CREATED";
	
	String EMAIL_TYPE_IMAGING_REPORT_FINISHED = "EMAIL_TYPE_IMAGING_REPORT_FINISHED";
	
}
